spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trello_db
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: db/changelog/main-changelog.xml
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
security:
  jwt:
    secret-key: veryLongAndVerySecretKeyNoBodyWillEverGuessItBecauseItIsUnbelievablySecretOhMyLordSomeOneTryToGuessIt
upload-server:
  url: http://localhost:8081
